---
title: "freedom"
author: "Kalyani Cauwenberghs"
date: "1/21/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Read in data and split into groups
```{r eval=FALSE}
data<-read.csv("hfi_cc_2019.csv")

#find the number of "-"'s in the row pf_rol_procedural
#sum(data$pf_rol_procedural=="-")

#number of observations for each region
#summary(data$region)

#add a region column to the data
data<-cbind(data.frame("REGION" = numeric(nrow(data))),data)
for(i in 1:nrow(data)){
  if (data$region[i]=="South Asia"|
      data$region[i]=="Caucasus & Central Asia"|
      data$region[i]=="Oceania"|
      data$region[i]=="East Asia"){
    data$REGION[i]<-"asia_oceania"
  } else if (data$region[i]=="Eastern Europe"|
             data$region[i]=="Western Europe") {
    data$REGION[i]<-"europe"
  } else if (data$region[i]=="Middle East & North Africa"|
             data$region[i]=="Sub-Saharan Africa") {
    data$REGION[i]<-"africa"
  } else if (data$region[i]=="North America"|
             data$region[i]=="Latin America & the Caribbean") {
    data$REGION[i]<-"americas"
  }
}

#split the data into groups
asia_oceania<-data[data$region=="South Asia"|
                     data$region=="Caucasus & Central Asia"|
                     data$region=="Oceania"|
                     data$region=="East Asia",]
europe<-data[data$region=="Eastern Europe"|
             data$region=="Western Europe",]
africa<-data[data$region=="Middle East & North Africa"|
             data$region=="Sub-Saharan Africa",]
americas<-data[data$region=="North America"|
               data$region=="Latin America & the Caribbean",]
```



## Plot histograms, densities, and boxplots for the continuous variables (hf_score, ef_regulation_credit_private)
```{r eval=FALSE}
#hf_score, ef_regulation_credit_private
asia_hf_score<-as.numeric(asia_oceania$hf_score[asia_oceania$hf_score!="-"])
europe_hf_score<-as.numeric(europe$hf_score[europe$hf_score!="-"])
africa_hf_score<-as.numeric(africa$hf_score[africa$hf_score!="-"])
americas_hf_score<-as.numeric(americas$hf_score[americas$hf_score!="-"])

#density
min<-min(as.numeric(data$hf_score))
max<-max(as.numeric(data$hf_score))
plot(density(europe_hf_score),xlim=c(min-20,max+50), col="red", main="Human Freedom Score by Region")
lines(density(asia_hf_score),col="green")
lines(density(africa_hf_score), col = "blue")
lines(density(americas_hf_score), col = "purple")
legend(1,95,legend=c("Europe","Asia_Oceania","Africa","Americas"), fill=c("red","green","blue","purple"))

#boxplot
boxplot(asia_hf_score,europe_hf_score,africa_hf_score,americas_hf_score,
        names = c("asia_oceania","europe","africa","americas"),
        main="Human Freedom Score by Region")

#histogram
hist(europe_hf_score, main = "Human Freedom Score Europe")
hist(asia_hf_score, main = "Human Freedom Score Asia_Oceania")
hist(africa_hf_score, main = "Human Freedom Score Africa")
hist(americas_hf_score, main = "Human Freedom Score Americas")

```
```{r eval=FALSE}
#ef_regulation_credit_private
asia_<-as.numeric(asia_oceania$ef_regulation_credit_private[asia_oceania$ef_regulation_credit_private!="-"])
europe_<-as.numeric(europe$ef_regulation_credit_private[europe$ef_regulation_credit_private!="-"])
africa_<-as.numeric(africa$ef_regulation_credit_private[africa$ef_regulation_credit_private!="-"])
americas_<-as.numeric(americas$ef_regulation_credit_private[americas$ef_regulation_credit_private!="-"])

#density
min<-min(as.numeric(data$ef_regulation_credit_private))
max<-max(as.numeric(data$ef_regulation_credit_private))
plot(density(europe_),xlim=c(min-20,max+50), col="red", main="ef_regulation_credit_private by Region")
lines(density(asia_),col="green")
lines(density(africa_), col = "blue")
lines(density(americas_), col = "purple")
legend(1,95,legend=c("Europe","Asia_Oceania","Africa","Americas"),
       fill=c("red","green","blue","purple"))

#boxplot
boxplot(asia_,europe_,africa_,americas_,
        names = c("asia_oceania","europe","africa","americas"),
        main="ef_regulation_credit_private by Region")

#histogram
hist(europe_, main = "ef_regulation_credit_private Europe")
hist(asia_, main = "ef_regulation_credit_private Asia_Oceania")
hist(africa_, main = "ef_regulation_credit_private Africa")
hist(americas_, main = "ef_regulation_credit_private Americas")

```
```{r eval=FALSE}
#ef_government
asia_<-as.numeric(asia_oceania$ef_government[asia_oceania$ef_government!="-"])
europe_<-as.numeric(europe$ef_government[europe$ef_government!="-"])
africa_<-as.numeric(africa$ef_government[africa$ef_government!="-"])
americas_<-as.numeric(americas$ef_government[americas$ef_government!="-"])

#density
min<-min(as.numeric(data$ef_government))
max<-max(as.numeric(data$ef_government))
plot(density(europe_),xlim=c(min-20,max+50), col="red", main="ef_government by Region")
lines(density(asia_),col="green")
lines(density(africa_), col = "blue")
lines(density(americas_), col = "purple")
legend(1,95,legend=c("Europe","Asia_Oceania","Africa","Americas"),
       fill=c("red","green","blue","purple"))

#boxplot
boxplot(asia_,europe_,africa_,americas_,
        names = c("asia_oceania","europe","africa","americas"),
        main="ef_government by Region")

#histogram
hist(europe_, main = "ef_government Europe")
hist(asia_, main = "ef_government Asia_Oceania")
hist(africa_, main = "ef_government Africa")
hist(americas_, main = "ef_government Americas")

```



## Plot bar plots for the discrete variables (ef_government_enterprises, ef_government, year, hf_quartile)
```{r eval=FALSE}
#quartile: lower = better
df<-data[,c(1,8)]
df<-df[df$hf_quartile!="-",]
asia<-df[which(df$REGION=="asia_oceania"),]
europe<-df[which(df$REGION=="europe"),]
africa<-df[which(df$REGION=="africa"),]
americas<-df[which(df$REGION=="americas"),]

mydf <- data.frame( 
  One=c(
    Europe=sum(europe$hf_quartile==1), 
    Asia_Oceania=sum(asia$hf_quartile==1), 
    Americas=sum(americas$hf_quartile==1),
    Africa=sum(africa$hf_quartile==1)
  ), 
  Two=c(
    Europe=sum(europe$hf_quartile==2),
    Asia_Oceania=sum(asia$hf_quartile==2),
    Americas=sum(americas$hf_quartile==2),
    Africa=sum(africa$hf_quartile==2)
  ), 
  Three=c(
    Europe=sum(europe$hf_quartile==3),
    Asia_Oceania=sum(asia$hf_quartile==3),
    Americas=sum(americas$hf_quartile==3),
    Africa=sum(africa$hf_quartile==3)
  ), 
  Four=c(
    Europe=sum(europe$hf_quartile==4),
    Asia_Oceania=sum(asia$hf_quartile==4),
    Americas=sum(americas$hf_quartile==4),
    Africa=sum(africa$hf_quartile==4)
  ) 
  )
barplot(t(as.matrix(mydf)), beside=TRUE, 
        legend = colnames(mydf), args.legend = list(x="top",cex = .7),
        main="Region vs. Human Freedom Score Quartile")


```

```{r eval = FALSE}
#ef_government_enterprises
df<-data[,c(1,66)]
df<-df[df$ef_government_enterprises!="-",]
asia<-df[which(df$REGION=="asia_oceania"),]
europe<-df[which(df$REGION=="europe"),]
africa<-df[which(df$REGION=="africa"),]
americas<-df[which(df$REGION=="americas"),]

mydf <- data.frame( 
  Zero=c(
    Europe=sum(europe$ef_government_enterprises==0), 
    Asia_Oceania=sum(asia$ef_government_enterprises==0), 
    Americas=sum(americas$ef_government_enterprises==0),
    Africa=sum(africa$ef_government_enterprises==0)
  ), 
  Two=c(
    Europe=sum(europe$ef_government_enterprises==2),
    Asia_Oceania=sum(asia$ef_government_enterprises==2),
    Americas=sum(americas$ef_government_enterprises==2),
    Africa=sum(africa$ef_government_enterprises==2)
  ), 
  Four=c(
    Europe=sum(europe$ef_government_enterprises==4),
    Asia_Oceania=sum(asia$ef_government_enterprises==4),
    Americas=sum(americas$ef_government_enterprises==4),
    Africa=sum(africa$ef_government_enterprises==4)
  ), 
  Six=c(
    Europe=sum(europe$ef_government_enterprises==6),
    Asia_Oceania=sum(asia$ef_government_enterprises==6),
    Americas=sum(americas$ef_government_enterprises==6),
    Africa=sum(africa$ef_government_enterprises==6)
  ), 
  Seven=c(
    Europe=sum(europe$ef_government_enterprises==7),
    Asia_Oceania=sum(asia$ef_government_enterprises==7),
    Americas=sum(americas$ef_government_enterprises==7),
    Africa=sum(africa$ef_government_enterprises==7)
  ), 
  Eight=c(
    Europe=sum(europe$ef_government_enterprises==8),
    Asia_Oceania=sum(asia$ef_government_enterprises==8),
    Americas=sum(americas$ef_government_enterprises==8),
    Africa=sum(africa$ef_government_enterprises==8)
  ), 
  Ten=c(
    Europe=sum(europe$ef_government_enterprises==10),
    Asia_Oceania=sum(asia$ef_government_enterprises==10),
    Americas=sum(americas$ef_government_enterprises==10),
    Africa=sum(africa$ef_government_enterprises==10)
  ) 
  )
barplot(t(as.matrix(mydf)), beside=TRUE, 
        legend = colnames(mydf), 
        args.legend = list(x="top",cex = .7),
        main="Region vs. Government Enterprises")


```
```{r eval = FALSE}
#ef_government
df<-data[,c(1,71)]
df<-df[df$ef_government!="-",]
asia<-df[which(df$REGION=="asia_oceania"),]
europe<-df[which(df$REGION=="europe"),]
africa<-df[which(df$REGION=="africa"),]
americas<-df[which(df$REGION=="americas"),]

mydf <- data.frame( 
  Zero=c(
    Europe=sum(europe$ef_government_enterprises==0), 
    Asia_Oceania=sum(asia$ef_government_enterprises==0), 
    Americas=sum(americas$ef_government_enterprises==0),
    Africa=sum(africa$ef_government_enterprises==0)
  ), 
  Two=c(
    Europe=sum(europe$ef_government_enterprises==2),
    Asia_Oceania=sum(asia$ef_government_enterprises==2),
    Americas=sum(americas$ef_government_enterprises==2),
    Africa=sum(africa$ef_government_enterprises==2)
  ), 
  Four=c(
    Europe=sum(europe$ef_government_enterprises==4),
    Asia_Oceania=sum(asia$ef_government_enterprises==4),
    Americas=sum(americas$ef_government_enterprises==4),
    Africa=sum(africa$ef_government_enterprises==4)
  ), 
  Six=c(
    Europe=sum(europe$ef_government_enterprises==6),
    Asia_Oceania=sum(asia$ef_government_enterprises==6),
    Americas=sum(americas$ef_government_enterprises==6),
    Africa=sum(africa$ef_government_enterprises==6)
  ), 
  Seven=c(
    Europe=sum(europe$ef_government_enterprises==7),
    Asia_Oceania=sum(asia$ef_government_enterprises==7),
    Americas=sum(americas$ef_government_enterprises==7),
    Africa=sum(africa$ef_government_enterprises==7)
  ), 
  Eight=c(
    Europe=sum(europe$ef_government_enterprises==8),
    Asia_Oceania=sum(asia$ef_government_enterprises==8),
    Americas=sum(americas$ef_government_enterprises==8),
    Africa=sum(africa$ef_government_enterprises==8)
  ), 
  Ten=c(
    Europe=sum(europe$ef_government_enterprises==10),
    Asia_Oceania=sum(asia$ef_government_enterprises==10),
    Americas=sum(americas$ef_government_enterprises==10),
    Africa=sum(africa$ef_government_enterprises==10)
  ) 
  )
barplot(t(as.matrix(mydf)), beside=TRUE, 
        legend = colnames(mydf), 
        args.legend = list(x="top",cex = .7),
        main="Region vs. Government Enterprises")


```





